[package]
name = "mock"
version = "0.1.0"
edition = "2021"
description = "A reference implementation of siling only made for tests"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
siling = { path = "../siling" }
